spring:
  datasource:
    platform: h2
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
    show-sql: true
  data:
    rest:
      enable-enum-translation: true

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG

server:
  port: 12345